### PR TITLE
Milestone 2

### PR DESCRIPTION
**Pull request by Davidosky007**
# Social Media Website
In this milestone, I 
*  created a friendship model
* created an association between friendship, user, posts, likes and comments.
* created all required feature for friendship

### CODE REVIEW

**Review by rindrajosia — CHANGES_REQUESTED** [review]
**Changes required**
Hello!!
You did a very good job.
However, to move forward you have to make some changes:
REQUIRED:
- [ ] Put database config` as default`:

Please delete these lines because we don't have the same database config.

- [ ] Delete this migration because it causes an error when I migrate the database, as you can see, you _are trying to delete_ `friendships` _before creating it_.


- [ ] User can invite friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] User can see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ]  User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] There is a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))




You should `add a button to invite user to friendship` on these pages.

- [ ] I should be able to see only "Posts" written by me and my friends.([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

As you can see in this screenshot, Josia is not yet Marina's friend however, Josia can see Marina's Post.

Please, make the suggested changes and submit a new code review request
Thanks
Rindra Josia

**Review by oloomoses — CHANGES_REQUESTED** [review]
# Status: Changes Required
Hello Team, you are progressing so well on this project. :muscle: Kindly check that you implement  the changes below before submitting for another review :point_down: 

## Required:

- [ ] Ensure that your linter is configured correctly and all the checks are passing
- [ ] Kindly change your DB config as requested by the previous review on the first point and the second
- [ ] Ensure that the RSpec is configured correctly and all the tests are passing.
- [ ] Add a button to unfriend an existing friend

## Feel free to contact me on slack [OLoo Moses]() in case of doubts or concerns
# Oloo Moses

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Required Changes 🛑♻**

<hr>

Hello there, You've done a good job working on this project, but there is a small issue you need to fix in order to complete it.

## **[Mandatory]**

- [ ] There's an error in your database migrations (as mentioned earlier by previous reviewers) you need to fix this. I'll give you a hint: first, you need to re-migrate your database. Please run ```rails db:migrate VERSION=0``` in your terminal in order to rollback the whole schema to the beginning (don't worry it won't delete any of your migrations) after you do that you should see your schema empty, then think about your migrations and ORDER them correctly, remove the error causing one and then run ```rails db:migrate``` again!
Screenshot

- [ ] You should fix the above error in order to make your tests run properly tho.

<hr>

## **[OPTIONAL]**

- It'd not take more than 5 mins to deploy your app on Heroku or Netlify and attach the link in your README file for easier access

Please fix this issue and you should be good to go 😊🙏

Good luck and happy coding 👨‍💻💻

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @Davidosky007**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] when a user A send a friend request to user B. make sure to add the actions to accept or decline the friendship on the users/ route for User B as in the friendship view. 


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi 

Such a remarkable project you made :+1: ! Awesome README :100: !

Good job with the changes! :tada: We are almost there.

We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.

- [ ]  There is an issue with running `rails db:create` and `rails db:migrate`. Please fix it.

##

- **When you have made the specified changes, please submit another code review. Thank you!**

##

**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**

HAPPY CODING :computer:

**[Umair Arshad](https://umairarshad.me/)**

[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by Davidosky007** [comment]
> # Status: REQUIRED CHANGES ⚠️ 🚧
> Hi
> 
> Such a remarkable project you made 👍 ! Awesome README 💯 !
> 
> Good job with the changes! 🎉 We are almost there.
> 
> We, however, do have a few changes to carry out before we proceed (see review comment).
> 
> For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
> 
> * [ ]   There is an issue with running `rails db:create` and `rails db:migrate`. Please fix it.
> 
> * **When you have made the specified changes, please submit another code review. Thank you!**
> 
> **If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
> 
> HAPPY CODING 💻
> 
> **[Umair Arshad](https://umairarshad.me/)**
> 
> [Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

hey please I don't know what else to do, I have deleted and created another schema and it works perfectly on my local system if you can help that would be great

**Pull request closed without merging**
